@startuml beautiful


class DateTime {
    year: number
    month: number
    day: number
    hour: number
    minute: number
    second: number
    millisecond: number
    unixMs: number
    ---
    toDate(): Date
    add({year: number, month: number, ..., second: number, ms: number}): DateTime
    format(pattern: string): string
}


class FooCalendar <<ExternalLibrary>> {
    events: FooCalendarEvent[]
}

interface FooCalendarEvent <<ExternalLibrary>> {
    title: string
    description: string
    start: number
    end: number
}

class TimeFrame {
    start: DateTime
    end: DateTime
    length: number
    ---
    intersects(TimeFrame): bool
    moveTo(DateTime): void
    shift(ms: number): void
    extend(ms: number): void
    findNext(TimeFrame[]): TimeFrame
}


class FooCalendarEventImpl implements FooCalendarEvent {
    timeFrame: TimeFrame
}


FooCalendar "1" --o "0..n" FooCalendarEvent

TimeFrame "1" --o "2" DateTime

FooCalendarEventImpl "1" --o "1" TimeFrame

@enduml
