@startuml ugly

class DateUtil {
    getLength(CalendarEvent): number
    add(Date, {year: number, month: number, ..., second: number, ms: number}): void
    moveTo(CalendarEvent, Date): void
    shift(CalendarEvent, time: number): void
    extend(CalendarEvent, time: number): void
    format(CalendarEvent, pattern: string): string
    intersects(CalendarEvent, CalendarEvent): bool
    findNext(CalendarEvent, CalendarEvent[]): CalendarEvent
}

class Date <<Built-in>> {
    ---
    getFullYear(): number
    getMonth(): number
    getDate(): number
    getHours(): number
    getMinutes(): number
    getSeconds(): number
    getMillseconds(): number
    getTime(): number
}

class FooCalendar <<ExternalLibrary>> {
    events: FooCalendarEvent[]
}

interface FooCalendarEvent <<ExternalLibrary>> {
    title: string
    description: string
    start: number
    end: number
}


FooCalendar "1" --o "0..n" FooCalendarEvent

DateUtil -> FooCalendarEvent : process
DateUtil --> Date : process

@enduml
