@startuml ugly

component PageComponent

component FormComponent [
    FormComponent
    ----
{{
salt
{
" First Name "
" Last Name "
" E-mail "
}
}}
]

PageComponent --> FormComponent : prop { firstName: "...", \n lastName: "...", \n email: "..." }
PageComponent <-- FormComponent : event("firstName", "...")
PageComponent <-- FormComponent : event("lastName", "...")
PageComponent <-- FormComponent : event("email", "...")

@enduml


@startuml beautiful

component PageComponent

component FormComponent [
    FormComponent
    ----
{{
salt
" First Name "
" Last Name "
" E-mail "
}}
]

PageComponent --> FormComponent : prop { firstName: "...", \n lastName: "...", \n email: "..." }
PageComponent <-- FormComponent : event("change", { firstName: "...", \n lastName: "...", \n email: "..." })

@enduml
